language: java
before_install:
  - echo $GPG_SECRET_KEYS | base64 --decode | $GPG_EXECUTABLE --import --batch || true
matrix:
  include:
    - jdk: openjdk7
      dist: trusty
    - jdk: openjdk8
      dist: xenial
    - jdk: openjdk11
      dist: xenial
    - jdk: oraclejdk7
      dist: precise
    - jdk: oraclejdk8
      dist: trusty
    - jdk: oraclejdk11
      dist: trusty
  allow_failures:
    - jdk: openjdk7
    - jdk: oraclejdk7
before_script:
  - "./scripts/startPrism.sh &"
  - sleep 20
install:
  - mvn --settings .maven.xml install -DskipTests=true -Dgpg.skip -Dmaven.javadoc.skip=true -B -V
deploy:
  - provider: script
    script: mvn clean deploy --settings .maven.xml -DskipTests=true -B -U -Prelease
    edge: true
    on:
      tags: true
      jdk: openjdk8
      branch: master

notifications:
  slack:
    if: branch = master
    on_success: never
    on_failure: change
    rooms:
      - secure: q2SEemDXFLu/2G2I7oD02+YsM5Q0G27j+b4P1BcReWqVHhRz9L+iyuYWhIXJ6hW0omL5V2XrZ65uqb4f/SD7b89oXRGToVxfykrBzcas1tqIIp9lldd1u2eMc59zALX4nkTlE0T4UFLwEvoeY8aXoD/dNytSy6M2F5c2nYcmoN0=
